[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-client-transports = "15.0"
jsonrpc-core = "15.0"
futures = "0.1.26"

[dev-dependencies]
hyper = "0.12"
